# The Docker Config version. Do not change.
version: "3.8"
services: 

  frontend:
    image: docker_workshop
    container_name: angry_wilson
    ports: 
      - 3000:3000
    networks:
      - app-network 

  server:
    image: api_123
    container_name: jolly_wilson
    ports: 
      - 8089:8089
    networks:
      - app-network 

  db:
    image: postgres
    container_name: silly_willy
    ports: 
      - 5432:5432
    volumes:
       - ./docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: workshop
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge