# Specify the node base image with your desired version, e.g. node:<version>
FROM node:alpine

# Set and create the working directory for this app
WORKDIR /api

# Copy this application's files from the current directory to the filesystem
# of the container at /app
COPY . /api

# Make the container accept traffic on port <port> at runtime from other
# containers or the host if also published
EXPOSE 8083

# Run this shell command at build time
RUN npm install
RUN npm install nodemon

# Start the application
CMD [ "npm",  "start" ]

